import "@testing-library/jest-dom";

process.env.NEXT_PUBLIC_PROJECT_ID = "13eecb85-e8da-4d6a-b356-0ac6f4c20caa"
process.env.NEXT_PUBLIC_PRIVATE_KEY = "6cb966c1-f3c2-4a14-995b-e234738cd37a"
process.env.NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCfccttFJcuzZZ-d0FHJ6BdB2qI0SXWE6Q"
process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "xline-8040b.firebaseapp.com"
process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID = "xline-8040b"
process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "xline-8040b.appspot.com"
process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "806248780207"
process.env.NEXT_PUBLIC_FIREBASE_APP_ID = "1:806248780207:web:a0b90b7c594e709db65f5a"
process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-MDC0CVBWM3"
process.env.NEXT_PUBLIC_COMMON_ROOM_ID = "BcUBzGOIGOqtLSqBaRNT"
process.env.NEXT_PUBLIC_CLOUDINARY_URL = "https://api.cloudinary.com/v1_1/dotwawzhk/image/upload"
process.env.NEXT_PUBLIC_CLOUD_NAME = "dotwawzhk"
process.env.NEXT_PUBLIC_PRESET = "nextbit"
